### ISSUE TITLE
Argument 1 passed to TypeDeducer::deduceTypesFromNode() must implement interface PhpParser\Node, null given

### ISSUE THREAD

**Issue by eigan** [php-integrator/core#53]
Get these errors after upgrading to 2.0 and running index.

Seems like the plugins depending on integrator-base stopped working too.

```
The socket server sent back something unexpected. This could be a bug, but it could also be a problem with your setup. If you're sure it is a bug, feel free to report it on the bug tracker.
```

```
Argument 1 passed to PhpIntegrator\Analysis\Typing\TypeDeducer::deduceTypesFromNode() must implement interface PhpParser\Node, null given, called in /home/einar/.atom/packages/php-integrator-core/src/Indexing/FileIndexer.php on line 575
```

From the dev console:
```
The PHP server has errors to report: PHP Notice:  Undefined offset: 0 in /home/einar/.atom/packages/php-integrator-core/src/Indexing/FileIndexer.php on line 572
```

PHP: 7.0.14
Atom: 1.12.7
Electron: 1.4.12
Chrome: 53.0.2785.143
Node: 6.5.0
OS: Arch Linux

**Comment by eigan** [comment]
Tried setting up on a new project (this repo), worked.

**Comment by Gert-dev** [comment]
This seems like a logic error on my end: a default value for a property can't be parsed correctly. I can do a quick fix by ignoring the default value if it fails, but in fact it should never fail as all default values for property should be seen as valid PHP code and at least return a single node.

Could you navigate to the file and line in question (`FileIndexer:575`) and try echoing the `$rawData['defaultValue']` that is passed? Restarting Atom and letting the index fail again should then show it in the developer tools.

Based on the default value, I can hopefully figure out what I missed. I already tried a few large codebases such as Symfony and libraries written in older PHP code such as tcpdf (which yielded a few corner cases I didn't expect) before I released, but it seems I missed some more.

**Comment by eigan** [comment]
Default value: `Department::class`

The complete line:
```
public $entity = Department::class;
```

**Comment by Gert-dev** [comment]
GitHub autoclosed this, but I've just released core and base 2.0.1 that should fix this issue.

**Comment by eigan** [comment]
Thank you, it works now! :+1: 

Though I did have some issues updating. I tried restarting, but each time, atom tried reinstalling the atom-integrator-core package. After the installtion was complete, an error was triggered telling that the PHP server could not start. Seems to be fixed when I uninstalled php-integrator-core, then restartet Atom.. I think.

_Maybe it has anything to do with php-integrator-core still at 2.0.0?_

**Comment by Gert-dev** [comment]
Yes, I forgot to bump the core version number after updating the base package to 2.0.1, causing the core to be redownloaded constantly [1]. That the core isn't inside the atom base package anymore is an improvement, but the way it is installed automatically can certainly use some more work [2].

[1] https://github.com/php-integrator/atom-base/issues/253
[2] https://github.com/php-integrator/atom-base/issues/254
