### ISSUE TITLE
php-integrator-core fails on install as base dependency

### ISSUE THREAD

**Issue by Yamakasi** [php-integrator/core#64]
I have installed php-integrator-base which needs php-integrator-core which fails:

D:\PortableApps\AtomPortable_1.12.7\Data\atom\packages\svn\lib\svn-utils.coffee:310 SVN svn-utils TypeError: Cannot read property 'toString' of null(…)Repository.handleSvnError @ D:\PortableApps\AtomPortable_1.12.7\Data\atom\packages\svn\lib\svn-utils.coffee:310
D:\PortableApps\AtomPortable_1.12.7\App\Atom\resources\app.asar\src\text-editor-component.js:975 /deep/ combinator is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
D:\PortableApps\AtomPortable_1.12.7\App\Atom\resources\app.asar\src\text-editor-component.js:975 ::shadow pseudo-element is deprecated. See https://www.chromestatus.com/features/6750456638341120 for more details.
https://api.github.com/search/issues?q=Failed%20to%20activate%20the%20linter%20package%20repo:atom-community/linter&sort=created Failed to load resource: the server responded with a status of 422 (Unprocessable Entity)
D:\PortableApps\AtomPortable_1.12.7\Data\atom\packages\linter-puppet-lint\node_modules\sb-exec\lib\helpers.js:159 Uncaught (in promise) Error: spawn puppet-lint ENOENT(…)
https://is.gd/create.php?format=simple Failed to load resource: the server responded with a status of 400 ()
D:\PortableApps\AtomPortable_1.12.7\App\Atom\resources\app.asar\node_modules\jquery\dist\jquery.js:3256 Uncaught (in promise) Object
D:\PortableApps\AtomPortable_1.12.7\Data\atom\packages\php-integrator-base\node_modules\atom-package-deps\lib\view.js:69 [Package-Deps] Unable to install php-integrator-core , Error: INFO: Could not find files for the given pattern(s).
The system cannot find the file specified.
Cannot read property 'getReferenceTarget' of nullcomplete @ D:\PortableApps\AtomPortable_1.12.7\Data\atom\packages\php-integrator-base\node_modules\atom-package-deps\lib\view.js:69

Any idea how to fix this ?

**Comment by Gert-dev** [comment]
This seems like an issue with your Atom installation or something like no internet connection being present. What you can try is running `apm install php-integrator/core` manually to see if that has any effect.

**Comment by infomaniac50** [comment]
I'm getting an error that says "Path must be a string".

Just for kicks I made a backup of my apm directory and wiped it. I then tried to install it again

[![asciicast](https://asciinema.org/a/97017.png)](https://asciinema.org/a/97017)

```bash
infomaniac50@home ~
λ apm --version
apm  1.12.9
npm  3.10.5
node 4.4.5
python 2.7.12
git 2.7.4

infomaniac50@home ~
λ atom --version
Atom    : 1.12.7
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0
```

**Comment by Gert-dev** [comment]
My response was rather poorly timed as I've just released php-integrator-base 2.1.0, which doesn't need the core package installed via apm anymore. Instead, after updating, it should automatically pull it via Composer (working via apm to do this wasn't a good idea).

**Comment by infomaniac50** [comment]
I uninstalled the core package manually. Then I started Atom it notified me the core package was being downloaded.

Thanks for the quick turnaround. :smiley:

**Comment by Gert-dev** [comment]
Nice to hear! For others bumping into this thread, see also https://github.com/php-integrator/core/issues/69 .
