### ISSUE TITLE
Updating / Installing error: path must be a string

### ISSUE THREAD

**Issue by lukasoppermann** [php-integrator/core#71]
I tried everything from: https://github.com/php-integrator/core/issues/69
- uninstalling core and reinstalling
- uninstalling core and base and only reinstalling base -> shows message that it downloads but afterwards it shows a message that download failed.

Don't know what else I can try to fix this?

**Comment by codigoinsano** [comment]
In the Developer tools it shows error: Error: Updating to latest sha failed.

![captura de tela 2017-01-05 as 10 43 39](https://cloud.githubusercontent.com/assets/18296776/21680953/da778354-d333-11e6-9253-eb6c08ec6154.png)

**Comment by Gert-dev** [comment]
@codigoinsano It seems you are still trying to update the php-integrator-core package? You should remove it from your installed packages.

**Comment by codigoinsano** [comment]
@Gert-dev When I tried to remove the package and install it again, the following error appeared:
![captura de tela 2017-01-05 as 20 00 59](https://cloud.githubusercontent.com/assets/18296776/21699271/08b49a2e-d382-11e6-975d-b66f0edec35a.png)

**Comment by Gert-dev** [comment]
@codigoinsano You don't need to reinstall the core package, you can just remove it and leave it that way. It is no longer required.

I must ask though: how are you reinstalling it in the first place? Via apm? It isn't in the official Atom package registry 😄 .

**Comment by fdinardo** [comment]
@Gert-dev :+1: Removing it doesn't create any problem and gets rid of the boring update notification message. Thanks a lot.

**Comment by Gert-dev** [comment]
I'll assume this is fixed as there have been no more reports. I've also taken this up in [the base package wiki](https://github.com/php-integrator/atom-base/wiki/Help!-It-Doesn't-Work!).
