### ISSUE TITLE
Doc small lack ?

### ISSUE THREAD

**Issue by Mageistral** [php-integrator/core#72]
Hello,
first of all, I'm on Windows.
Short in time version : after having the error "Core installation failed", I went to the directory to see what possibly go wrong. Then I saw the composer.json. The thing is I don't have composer in my global PATH. I ran the `composer install` command manually in the directory :
_C:\ProgrammesFixes\.atom\packages\php-integrator-base\core\2.1.1_
All the dependencies were fetched well during the process.
Your great package works now.

So, I would suggest to add in the "Awesome! What do I need?" a notice on having composer in the PATH.

Thanks again for your good work.

**Comment by Gert-dev** [comment]
Nice to hear that you got it working, but Composer isn't actually required to be installed. You are right however in that the core is fetched via Composer. The base package will automatically install and run a temporary Composer to install the core with using your configured PHP binary.

It could be that the base Composer failed downloading or that it didn't succeed running for some reason. In that case there should be some output in the developer tools. Installing it via your own Composer will work fine as well, as you're basically doing what the base package was trying to do :-).

I've been getting other questions about this as well so I decided to add the [Help! It Doesn't Work!](https://github.com/php-integrator/atom-base/wiki/Help!-It-Doesn't-Work!) page to the base package wiki for users experiencing the same issues.
