### ISSUE TITLE
Tooltips don't display parameter type when line finishes with a period.

### ISSUE THREAD

**Issue by Gert-dev** [php-integrator/core#73]
Note: originally reported by @thepenguin1 at https://github.com/php-integrator/atom-tooltips/issues/24.

Consider the following function / doc block:

```
/**
 * Create a custom error and add it to the error
 * message bag so it will be flashed to the session.
 * User is then redirected back, or to optional url.
 *
 * @param string $error.
 * @param string $url.
 * @param bool $force_json.
 * @return mixed.
 *
 **/
function abortWithError($error, $url = "", $force_json = false)
{
 ...
}
```

The resulting tooltip displays the parameters, but without their data type:

![screen shot 2017-01-19 at 11 09 20 am](https://cloud.githubusercontent.com/assets/19876593/22104572/d16b632a-de37-11e6-9392-84b22ddbaecc.png)

This appears to be caused by the period at the end of the parameter name.

**Comment by Gert-dev** [comment]
@thepenguin1 I've been thinking on this a bit more. The reason that this is going wrong is that the parameters in the docblock are not recognized as matching the actual parameters of the function, i.e. the parameter is called `$error`, but the docblock is defining a parameter called `$error.`. The parameter name may not be suffixed by a dot in this case.

If it is part of the description, there should be a space between the parameter name and the description. May I ask what you intended to achieve in this example or what your use case is and what you would have expected to happen in this case?

**Comment by thepenguin1** [comment]
My use case is where descriptions aren't always needed. The parameter name / data type is sufficient. 

So instead of:

Int $name [description].

This is sufficient:

Int $name.

**Comment by Gert-dev** [comment]
I see. Why are you adding a dot after the parameter name, though? [It is true that the description is optional](https://phpdoc.org/docs/latest/references/phpdoc/tags/param.html), but if you omit it, there also shouldn't be any trailing dot on the param line, as the only valid location for it is the description itself.

**Comment by thepenguin1** [comment]
You're probably right, I just like having the period at the end. It's a visual thing for me :)

**Comment by Gert-dev** [comment]
I could add an exception for it, but I'm a bit bound by the docblock specification. I'm also planning/hoping to move away from doing my own docblock parsing at some point in the future, in which case an exception will probably disappear again, so that unfortunately won't be of much help to you in that case ;-).

I'll close this as the behavior currently isn't actually bugged or invalid, but what you _could_ do, if you really want to keep the dot, is put a space between the parameter name and the dot. That would be valid docblock syntax and you get to keep the dot, albeit with a space between it, which may not look so great.

**Comment by thepenguin1** [comment]
Ok thanks :)
