### ISSUE TITLE
Update Error

### ISSUE THREAD

**Issue by RichieMcMullen** [php-integrator/core#80]
I'm receiving an error when trying to update to :  EFBEF7CD

`Error Message: path must be a string`

**Comment by Gert-dev** [comment]
Hello. It seems you are a victim of [the issue described here](https://github.com/php-integrator/atom-base/wiki/Help!-It-Doesn't-Work!#updating-to-latest-sha-failed--path-must-be-a-string) and [in this ticket](https://github.com/php-integrator/core/issues/71).
