### ISSUE TITLE
Non .php files

### ISSUE THREAD

**Issue by davidbarratt** [php-integrator/core#85]
Drupal uses `.module`, `.theme` and `.profile` extensions (as well as `.php`). However, it looks like non-php extensions are not indexed. Is there a way to instruct PHP integrator to index these files as well?

**Comment by Talv** [comment]
Yes. Initially atom-base plugin creates minimal configuration for your project:
```coffee
php:
  enabled: true
  php_integrator:
    enabled: true
    phpVersion: 7
    fileExtensions: [
      "php"
    ]
```
Which then can be expanded to your needs. See the wiki:
https://github.com/php-integrator/atom-base/wiki/Project-Settings

**Comment by davidbarratt** [comment]
Thanks!
